### ISSUE TITLE
Presets showing off screen in fixed mode

### ISSUE THREAD

**Issue by SicnarfG** [SyntaxBlitz/osrs-shattered-relics-fragment-presets#20]
![image](https://user-images.githubusercontent.com/100155836/155004333-78bc0dc9-c261-415c-81c5-2c7a9bf63a4c.png)

Can't access the other presets I have

**Comment by SyntaxBlitz** [comment]
@SicnarfG you should be able to turn off "Show import/export buttons" in the settings to get rid of the newly-added buttons. Did you turn this on explicitly? It should have defaulted to being off to prevent this from happening. Since you won't need those buttons very frequently, you can turn off that setting each time you're done using it; that's why the config option is there.

**Comment by SicnarfG** [comment]
[image: image.png]


Turned it off just like you said and some of my presets are still showing
off screen. The only way for me to access those presets is to put it in
resizable so I can make the screen bigger until I can see the presets. Is
there a way to add a scroll bar to the preset box to scroll up and down to
see the presets in fixed mode?

**Comment by SicnarfG** [comment]
![image](https://user-images.githubusercontent.com/100155836/155047477-cc6c3c91-279e-4bf2-9ddb-f41182c196df.png)


Turned it off just like you said and some of my presets are still showing off screen. The only way for me to access those presets is to put it in resizable so I can make the screen bigger until I can see the presets. Is there a way to add a scroll bar to the preset box to scroll up and down to see the presets in fixed mode?

**Comment by SyntaxBlitz** [comment]
Ah yes, in general I don't plan to resolve this overflow, unfortunately. Adding a scrollbar is out of scope for this project. Apologies!

**Comment by wizered67** [comment]
Hey @SyntaxBlitz, first of all thanks for writing this plugin, it's been invaluable for the league! I've found the overflow issue to be a bit annoying since it effectively limits the number of presets I can have. 

It's bugged me enough that I'm considering taking a (somewhat blind) stab at implementing a solution, if I'm feeling particularly ambitious over the weekend. I've never written a RuneLite plugin before, but I do have coding experience. On the off chance that I do get something working, would you be open to accepting a PR? Also, any tips you have for me would be much appreciated :) Thanks!

**Comment by SyntaxBlitz** [comment]
@wizered67 I'd be open to accepting a PR! My suggestion would be to find a way to avoid cluttering the interface too much, otherwise I'd probably want to keep it locked behind an off-by-default config setting to avoid disrupting users. If I were to write a minimal-effort implementation, I would probably store multiple numbered preset 'groups' and just use the config UI to switch which preset group is currently being shown/edited (instead of adding any new buttons in the main interface). Not that I'm recommending this as the best way to go about it, but at least it would be easy to implement. You'd need to make sure there's a migration path for old configs, as well.

My best tip, if you're using IntelliJ IDEA, would be to use the hot-reload functionality so you don't need to restart RuneLite every time you make a change. In fact, it may even be worth writing version 0 of your code in a way that lets you hot-reload more often (without changing any method signatures, which requires a restart). For example, you might use a for-loop instead of a lambda or write some code inline instead of extracting it into a separate function, at least while you're prototyping, because it speeds up the workflow so dramatically. You can always clean up dirty code afterwards (or, if you're like me, just decide to publish as-is because the whole gamemode will vanish in a few weeks anyway).

Good luck! I'm rooting for you. I'm only holding back on doing it myself because I have other priorities in my personal life at the moment. I'd still love to see the functionality in the project! Feel free to reach out on Discord (SyntaxBlitz#6719) if you have any questions.

**Comment by wizered67** [comment]
@SyntaxBlitz Thanks for the tips! I just opened a PR (https://github.com/SyntaxBlitz/osrs-shattered-relics-fragment-presets/pull/21) that attempts to address this by adding simple pagination. Would love to get your 👀 on it and hopefully get it merged!

@SicnarfG Since you were the one that originally raised this issue, feel free to leave any feedback on the UX and whether it would solve your problem!

**Comment by SyntaxBlitz** [comment]
#21 merged, closing this issue
